spring:
  datasource:
    url: ${SQLBUILDER_JDBC_URL:jdbc:oracle:thin:@localhost:1521/XEPDB1}
    username: ${SQLBUILDER_JDBC_USER:SB_USER}
    password: ${SQLBUILDER_JDBC_PASSWORD:sb_pass}
    driver-class-name: oracle.jdbc.OracleDriver

sqlbuilder:
  integration:
    dialect: oracle
